# Path configuration
path_to_data: C:\Users\lukas\Documents\HKA_DEV\HKA_EKG_Signalverarbeitung_Data\data
path_to_models: C:\Users\lukas\Documents\HKA_DEV\HKA_EKG_Signalverarbeitung_Data\models
path_to_matlab_data: C:\Users\lukas\Documents\HKA_DEV\HKA_EKG_Signalverarbeitung_Data\ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3\preprocessing_output

# Data preprocessing configuration
source_feature_list: ['P-wave', 'P-peak', 'QRS-complex', 'R-peak', 'T-wave', 'T-peak']
number_of_augmentations: 6      # augmentations per sample
normalization_method: 'min-max' # Options: 'min-max', 'z-score'

# Project seed configuration for reproducibility
seed: 42

# Data Module configuration
num_workers: 14
persistent_workers: True
sampling_rate: 512
feature_list: ['P-wave', 'P-peak', 'QRS-complex', 'R-peak', 'T-wave', 'T-peak']

# Model configuration (for training without using Hyperparameter Tuning)
batch_size: 32
max_epochs: 50
learning_rate: 0.001

# Wandb configuration
wandb_project_name: HKA-EKG-Signalverarbeitung
wandb_experiment_name: manual_training_1_lead

# Hypereparameter Tuning configuration (not all parameters are to be set in this config file)
number_of_trials: 5
hpo_batch_size: [16, 32, 64]
hpo_min_epochs: 3
hpo_max_epochs: 5
hpo_accumulate_grad_batches: [1, 2, 4, 8]
hpo_precision: [16-mixed, 32]
hpo_optimizers: ['Adam', 'SGD', 'AdamW']
hpo_min_learning_rate: 0.00005
hpo_max_learning_rate: 0.01
hpo_min_weight_decay: 0.00001
hpo_max_weight_decay: 0.01
hpo_scheduler: ['StepLR', 'CosineAnnealingLR', 'ReduceLROnPlateau']